#!/bin/sh
#
# $NetBSD: resize_disklabel,v 1.3 2018/10/06 09:58:55 jmcneill Exp $
#

# PROVIDE: resize_disklabel
# REQUIRE: fsck_root
# BEFORE: resize_root

$_rc_subr_loaded . /etc/rc.subr

name="resize_disklabel"
rcvar=$name
start_cmd="resize_disklabel_start"
stop_cmd=":"

get_rawpart()
{
	partno=$(/sbin/sysctl -n kern.rawpartition)
	test $partno = 2 && echo c || echo d
}

get_total_sectors()
{
	disk=$1
	/sbin/drvctl -p $disk disk-info/geometry/sectors-per-unit
}

get_rawpart_sectors()
{
	disk=$1
	rawpart=$2
	/sbin/disklabel $disk | grep "^ $rawpart:" | awk '{ print $2; }'
}

grow_mbrpart()
{
	disk=$1
	rawpart=$(get_rawpart)

	eval $(/sbin/fdisk -S $disk)
	if [ ! "$PART1SIZE" = "0" ]; then
	    warn "Partition #1 still exists"
	    return
	fi
	if [ ! "$PART0ID" = "169" ]; then
		warn "No NetBSD partition found in MBR partition #0"
		return
	fi

	ts=$(($(get_total_sectors $disk) - ${PART0START}))
	rs=${PART0SIZE}

	if [ "$ts" = "$rs" ]; then
		return
	fi

	oldsize=$(($rs * 512 / 1024 / 1024))
	newsize=$(($ts * 512 / 1024 / 1024))
	echo "Growing $disk MBR partition #0 (${oldsize}MB -> ${newsize}MB)"
	/sbin/fdisk -f -u -0 -s 169/${PART0START}/${ts} ${disk}
}

grow_disklabel()
{
	disk=$1
	part=$2
	rawpart=$(get_rawpart)

        eval $(/sbin/fdisk -S $disk)	
	
	ts=${PART0SIZE}
	rs=$(get_rawpart_sectors $disk a)

	if [ "$ts" = "$rs" ]; then
		return
	fi

	oldsize=$(($rs * 512 / 1024 / 1024))
	newsize=$(($ts * 512 / 1024 / 1024))
	echo "Growing $disk disklabel (${oldsize}MB -> ${newsize}MB)"
	printf "A\ny\nc\n\n\n\$\nd\n\n\n\$\nW\ny\nQ\n" | \
	    disklabel -i $disk >/dev/null
	printf "$part\n\n\n${PART0SIZE}\nb\n\n\n${PART1SIZE}\nW\ny\nQ\n" | \
	    disklabel -i $disk >/dev/null
}

resize_disklabel_start()
{
	if [ x"${resize_disklabel_disk}" = "x" ]; then
		resize_disklabel_disk="$(/sbin/sysctl -n kern.root_device)"
	fi
	if [ x"${resize_disklabel_part}" = "x" ]; then
		resize_disklabel_part=$(printf \\$(printf '%03o' $(( 97 + $(sysctl -n kern.root_partition) ))))
	fi

	grow_mbrpart "${resize_disklabel_disk}"
	grow_disklabel "${resize_disklabel_disk}" "${resize_disklabel_part}"
}

load_rc_config $name
run_rc_command "$1"
